/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./*.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#acb3ba",
        "secondary-container": "#ffdf96",
        "primary-fixed": "#5dbffe",
        "on-secondary-fixed": "#503c00",
        "on-background": "#2c3339",
        "primary-container": "#5dbffe",
        "surface-dim": "#d4dbe2",
        "tertiary": "#97473c",
        "inverse-surface": "#0b0f11",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#883c31",
        "on-error-container": "#6e0a12",
        "secondary-dim": "#685000",
        "background": "#f8f9fd",
        "surface-container": "#eaeef4",
        "inverse-on-surface": "#9b9da1",
        "secondary-fixed": "#ffdf96",
        "error-dim": "#67040d",
        "surface-container-low": "#f0f4f9",
        "on-surface": "#2c3339",
        "surface-variant": "#dde3eb",
        "on-primary-fixed": "#002032",
        "error-container": "#fa746f",
        "surface": "#f8f9fd",
        "on-secondary": "#fff8f0",
        "on-tertiary-container": "#5e1c14",
        "on-primary-fixed-variant": "#004261",
        "on-tertiary-fixed-variant": "#6a251c",
        "on-surface-variant": "#596066",
        "primary-dim": "#005981",
        "surface-tint": "#006592",
        "on-secondary-fixed-variant": "#735802",
        "on-tertiary": "#fff7f6",
        "secondary-fixed-dim": "#f6d075",
        "secondary": "#765b07",
        "primary": "#006592",
        "surface-container-high": "#e4e9ef",
        "tertiary-fixed": "#fd9889",
        "error": "#a83836",
        "tertiary-container": "#fd9889",
        "on-error": "#fff7f6",
        "on-tertiary-fixed": "#3d0402",
        "on-secondary-container": "#674e00",
        "tertiary-fixed-dim": "#ed8b7d",
        "inverse-primary": "#5dbffe",
        "on-primary-container": "#003854",
        "outline": "#757b82",
        "surface-container-highest": "#dde3eb",
        "surface-bright": "#f8f9fd",
        "on-primary": "#f5f9ff",
        "primary-fixed-dim": "#4db1ef"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: [],
}
